### ISSUE TITLE
Zobrazení dostupných streamů s datovým tokem

### ISSUE THREAD

**Issue by tprochazka** [bbaronSVK/plugin.video.stream-cinema#12]
Bylo by mnohem užitečnější, aby se při vybírání datového streamu zobrazoval datový tok jako 5Mbps místo celkové velikosti souboru, pro download pak má naopak smysl ta celková velikost. Klidně by tam mohlo být obojí, ale celkový velikost je pro streamování hodně matoucí.

**Comment by bbaronSVK** [comment]
Datovy tok je celkom dost zavadzajuci. Videa totiz nemaju CBR, alebo VBR a tym padom sa pocas celeho streamu meni Jediny datovy tok, ktory mame je len prepocet: velkost suboru / dlzka v sekundach. Niektory uzivatelia SC by z datoveho toku boli trocha mimo, lebo su menej technicky zdatny. Velkost suboru je podla mna dostacujuca.

**Comment by tprochazka** [comment]
Myslím si, že naopak většina lidí ví, jak rychlý má Internet a naopak vůbec netuší jak se z hodnoty 16 GB dostat na to, zda si to pustí. Ostatně plugin sám ten přepočet podle mě musí využívat, když se zapne automatický výběr streamu.

Bylo by možné to udělat alespoň jako optional v nastavení? 
Já bych to klidně udělal sám, ale zase se mi nechce udržovat si pak extra svou verzi a řešit každý update ručně mimo repository :-( Přece jen mám Kodi v telefonu, ve dvou PC a v TV
