### ISSUE TITLE
Stahování souborů s původním názvem

### ISSUE THREAD

**Issue by tprochazka** [bbaronSVK/plugin.video.stream-cinema#13]
API poskytuje originální název souboru  (jako Reboot.2012.720P.HDRIP.XViD.AC3-RESiSTANCE.avi) zatímco plugin je stahuje ve zcela smyšleném tvaru, což následně znemožňuje hledání titulků. Dávalo by určitě smysl zachovat originální název. když ho API poskytuje.

**Comment by bbaronSVK** [comment]
Je mi luto, ale stahovanie pod originalnym nazvom nebude mozne.

**Comment by tprochazka** [comment]
A můžu vědět proč, když je v API tento název k dispozici?
Například u seriálu je současný název úplně nepoužitelný.
