### ISSUE TITLE
Přidat do knihovny z výsledku hledání nefunguje

### ISSUE THREAD

**Issue by tprochazka** [bbaronSVK/plugin.video.stream-cinema#16]
Když seriál nebo film najdu podle abecedy je možné jej přidat do knihovny, ale pokud ho vyhledám přes hledání napíše to jen "No new content" a položka přidání s odběrem chybí úplně.

Bylo by strašně užitečné kdyby šlo do knihovny přidat i celou kategorii hlavně tedy ze sekce "Zoznamy/Rebricky", kde by se tak dalo přidat třeba všechny doporučené filmy a seriály do knihovny.

Aktuálně jde v nastavení jen zaškrnout "Automaticky přidat filmy do knihovny" a pak Skontrolovat nové částé a začne to rvát do knihovny úplně celou databázi Cinema CZ&SK, což není úplně ideální vzhledem k její velikosti.

**Comment by bbaronSVK** [comment]
sorry za neskoru reakciu, ale v niektorej starsej verzii bol bug, ze pri pridani do kniznice stale pisalo no new content. 
zo zoznamov/rebrickov sa daju filmy pridavat po jednom. Rovnako to plati aj vo vyhladavani.
