### ISSUE TITLE
Česká lokalizace

### ISSUE THREAD

**Issue by psimacek** [bbaronSVK/plugin.video.stream-cinema#21]
Česká verze se zřejmě s přibývajícími novými stringy míchá se slovenštinou. Mohl bych případně do cs přeložit. Jen nevím jak :-)

**Comment by bbaronSVK** [comment]
Staci prelozit tento subor: https://github.com/bbaronSVK/plugin.video.stream-cinema/blob/master/resources/language/Czech/strings.xml

**Comment by psimacek** [comment]
Díky, hotovo!

**Comment by bbaronSVK** [comment]
Mergol
Som to. V dalsej verzii to uz bude opravene
