### ISSUE TITLE
I po updatu na 1.3.1 to chce update

### ISSUE THREAD

**Issue by MartinZPC** [bbaronSVK/plugin.video.stream-cinema#23]
Ahoj,
aktualizováno na 1.3.1 a místo obsahu mi to píše Prosim updatnite plugin a Please, update your plugin.
Kodi 17.6 Krypton.

Není tam něco špatně v tom updatu?

Díky

**Comment by tprochazka** [comment]
Podle mě je problém v cache, jakmile se jednou načte to úvodní menu na staré verzi pluginu, server vrátí, že se má updatovat plugin, tak i po updatu to z nějakého důvodu, po nějakou dobu, pořád drží ten dříve načtený stav. Nechápu proč, protože nová verze mění URL na které se dotahuje, respektive přímo v URL je číslo verze API, takže by se to podle mě cachovat nemělo. Asi ta cache ignoruje parametry v URL. 

Každopádně se to vyřeší po nějaké době samo.

**Comment by bbaronSVK** [comment]
Kesuje si to priamo KODI - kesuje zoznam poloziek na disk. Malo by stacit restartovat kodi
