### ISSUE TITLE
Ahoj

### ISSUE THREAD

**Issue by Skalda555** [bbaronSVK/plugin.video.stream-cinema#3]
Nevim, asi to neni tvoje priorita, ale po update OSMC na Rapsberry mi prestal plugin fungovat a dost me to mrzi protoze je muj neojblibenejsi....

**Comment by sonics007** [comment]
treba log a potom ti moze pomoct

**Comment by bbaronSVK** [comment]
bez lepsieho popisu neviem pomoct.
