### ISSUE TITLE
nefunguje

### ISSUE THREAD

**Issue by puetro** [bbaronSVK/plugin.video.stream-cinema#4]
aktualna verzia 1.2.2 nefunguje (skusane na MAC aj ANDROID zariadeni)

chyba:
subor: "resources/lib/scutils.py" 
riadok 492

bud nechat "self...." bez zakomentovania, alebo zakomentovat aj predchadzajuci (aktualne prazdny) IF statement...

**Comment by bbaronSVK** [comment]
cau, dik za info .. chyba vznikla pri commite ... bol som az moc hyperaktivny a zabudol som, ze python potrebuje mat nieco v if
