### ISSUE TITLE
Stahování titulků k fimu

### ISSUE THREAD

**Issue by tprochazka** [bbaronSVK/plugin.video.stream-cinema#5]
Když stáhnu film, vytvoří se k souboru s filem je soubor titulků, ale vždy prázdný s 0B, i když online titulky jdou. Testováno třeba dnes na posledním dílu Big Bang Theory S11E02.

Btw. Nešlo by tam někde zobrazit co se vlastně stahuje a jaký je aktuálně progress? Nebo jsou ty popupy jediná možnost?

**Comment by bbaronSVK** [comment]
O stahovanie sa stara iny plugin (stream resolver) ja mu len posielam data ako do prehravaca. Mozem sa na to ale pozriet.

**Comment by tprochazka** [comment]
A stejný plugin řeší i stažení samotného filmu? Protože film se stáhne dobře.
Ono je vůbec škoda, že ještě nikdo nenapsal k otmu stahovači nějaké UI s přehledem co se stahuje.

**Comment by bbaronSVK** [comment]
asi preto, ze vsetci len streamuju. Malo kto stahuje, ale ja mam optiku, takze ja si to radsej hned pozriem ako keby som to mal stahovat a az potom pozerat. Ulozene to je na webshare, takze naco minat peniaze na ulozisko?

**Comment by tprochazka** [comment]
No, taky bych to rád sledoval rovonu, ale to se musím spokojit jen s 720p, jediná záchrana je HEVC, kdy pak v pohodě zvládnu i 1080p.

**Comment by bbaronSVK** [comment]
v 36ec21fc23e8e945808890720032d591bea7bb51 poriesene nove stahovanie.

**Comment by tprochazka** [comment]
Zkoušel jsem master a nefunguje to pořád, ale už vím proč ono totiž API vůbec nikdy nevrací cestu k těm titulkám tam kde to plugin při stahování hledá:

https://stream-cinema.online/kodi/Play/22071/1/1?lang=eng&ver=1.2&uid=eb1e7777-f9bb-4205-98c9-c200aaa26da5

subs klíč je vždy null a přesně na ten se dívá plugin při downloadu.
Nicméně při přehrávání se titulky odněkud jinud vezmou
