### ISSUE TITLE
Seriál Amazing race

### ISSUE THREAD

**Issue by Ryesen** [bbaronSVK/plugin.video.stream-cinema#7]
Ahoj, lze nějak přidat seriály do stream cinema knihovny? Konkrétně Amazing Race na webshare je, ale v KODI doplňku nikoliv.

Díky.

**Comment by bbaronSVK** [comment]
Ziadosti na novy obsah posielaj na forum: http://www.xbmc-kodi.cz/prispevek-ziadosti-na-novy-obsah?pid=23436#pid23436
